config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  root 'session#index'
  mount Sidekiq::Web, at: '/sidekiq'

  get '/session/notice' => 'session#notice'
  get '/session/index' => 'session#index'
  get 'session/first' => 'session#first'
  post '/session/login' => 'session#login'
  post 'session/profile' => 'session#profile'
  

  post '/user/confirm' => 'user#confirm', :as => 'confirm'
  post '/user/code' => 'user#code', :as => 'code'

  post '/user/profile' => 'user#profile', :as => 'profile'
  get 'user/profile' => 'user#profile', :as => 'userprofile'
  post 'user/delete' => 'user#delete', :as => 'delete'
  get 'user/logout' => 'user#logout', :as => 'logout'

  resources :user do 
    resources :train
  end
    post '/user/:id/train' => 'train#create', :as => 'create'
    get '/user/:id/stop' => 'user#stop', :as => 'stop'

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  skip_before_filter :verify_authenticity_token

  def notice
  end

  def index
    redirect_to user_path(User.find(session[:user_id])) if session[:user_id] != nil
  end

  def first
  end

  def login
    @user = get_user(params[:user])
    assign_session
  end

  def profile
    @user = User.find_by(params[:user][:pin])
    if @user.password_digest != params[:user][:pin]
      redirect_to session_notice_path
      flash[:notice] = "Pin is not correct."
    else
      session[:user_id] = @user.id
      redirect_to(profile_path(@user))
    end
      
  end

  protected

  def get_user(user_params)
    User.find_or_create_by(phone: user_params[:phone])
  end

  def get_pin(user_pin)
    User.find_by(password_digest: user_pin[:pin])
  end

end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/session/first.html.erb
<div class="phone splash">
	<div class="phone align">
		<%= form_for(:user, url: {action: "login"}, html: {class: "pure-form pure-form-stacked", id:'continue' }) do |f| %>
			<label class="lead">Please enter your cell phone number below:</label>
  		<%= f.text_field :phone, placeholder: '2225559909', id: "phone-number", maxlength: "10" %>
  		<br>
  		<input class="pure-button cta" type="submit" value="Continue">
		<% end %>
		<br><br><br>

			<label class="lead">Or log in with your Pin:</label>
  		<input class="pure-button cta" type="submit" value="Log in" id="show-form">
		<%= form_for(:user, url: {action: "profile"}, html: {class: "pure-form pure-form-stacked", id:'show' }) do |f| %>
			<label class="lead">Please enter your pin:</label><br> 
  		<%= f.text_field :pin, placeholder: '1234', id: "pin-number", maxlength: "4" %>
  		<br>
  		<input class="pure-button cta" type="submit" value="Continue">
		<% end %>
	</div>
</div>


	

	

app/views/session/index.html.erb
<div class="home splash">
	<div class="align">
		
		<h1 id="slogan">Get to work on time.</h1>
		
		<div class="lead">

			<p>Sign up, pick your stop and time, and get texted the stops information.</p>
		
		</div>

		<p>
			<type="button" class="pure-button cta"><%= link_to 'Get Started', session_notice_path %>
		</p>
	
	
	</div>
</div>

app/views/session/notice.html.erb
<div class="notice splash">
	<div class="confirm align">
		
		<h1 id="notice-header">Please Note:</h1>
		
		<div class="lead">

			<p id='message-center'>This app uses texting and is free to use. However, whatever your carrier normally charges to receive text messages still applies (most cell phone plans include unlimited texting).</p>
			
		</div>
		
		<div class ='pure-form-stacked'>

			<a href='/' type="button" id="back" class="pure-button cta delete notice">Go Back</a>

			<id="acknowledge" type="button" class="pure-button cta"><%= link_to 'Get Started', session_first_path %>

		</div>
		
	</div>
</div>