config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  root 'session#index'
  mount Sidekiq::Web, at: '/sidekiq'

  get '/session/notice' => 'session#notice'
  get '/session/index' => 'session#index'
  get 'session/first' => 'session#first'
  post '/session/login' => 'session#login'
  post 'session/profile' => 'session#profile'
  

  post '/user/confirm' => 'user#confirm', :as => 'confirm'
  post '/user/code' => 'user#code', :as => 'code'

  post '/user/profile' => 'user#profile', :as => 'profile'
  get 'user/profile' => 'user#profile', :as => 'userprofile'
  post 'user/delete' => 'user#delete', :as => 'delete'
  get 'user/logout' => 'user#logout', :as => 'logout'

  resources :user do 
    resources :train
  end
    post '/user/:id/train' => 'train#create', :as => 'create'
    get '/user/:id/stop' => 'user#stop', :as => 'stop'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :trains
  
  validates_uniqueness_of :phone
  validates_presence_of :phone
end

app/controllers/user_controller.rb
class UserController < ApplicationController


	def show
		@user = User.find(session[:user_id])
	end

	def confirm
		@user = User.find(session[:user_id])
		if @user.password_digest == params[:pin]
			redirect_to(user_path(@user))
		end
	end

	def code	
		@user = User.find(session[:user_id])
		generate_pin_save_user
		@client = create_client
	
		@client.account.messages.create(
			:body => "Message from CTA App:\nYour pin is #{assign_pin}.",
			:to => "+1#{@user.phone}",
			:from => ENV['FROM'])
		
		redirect_to(user_path(@user))
	end

	def profile
			@train = Train.new
			@user = User.find(session[:user_id])
			if params[:pin]
				if @user.password_digest != params[:pin] 
						redirect_to session_notice_path
						flash[:notice] = "Pin is not correct."
				end
			end
	end

  def stop
  	@user = User.find(session[:user_id])
  	render :"user/_stops_partial", :layout => false
  end

  def destroy
    @user = User.find(session[:user_id])
		if request.xhr?
        render :json => @user
    end
  end

  def delete
  	@user = User.destroy(session[:user_id])
  	session.clear
  	redirect_to root_path
  end

   def logout
    session.clear
    flash[:notice] = "See you next time."
    redirect_to root_path
  end




end

app/helpers/user_helper.rb
module UserHelper
	 def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    current_user != nil
  end

end

app/helpers/users_helper.rb
module UserHelper
	 def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    current_user != nil
  end

  def create_client
		account_sid = ENV['TWSID']
		auth_token = ENV['TOKEN']
		
		return Twilio::REST::Client.new(account_sid, auth_token)
	end



end

app/views/user/_stops_partial.html.erb
<% if @user.trains.any? %>
	
	<h1 id="stop-table-header">Your stops</h1>
	
	<hr align="left" class="divider">
	
	<table class="pure-table">
		
		<thead>

			<tr>
				<th>
					Stop
				</th>

				<th>
					Time
				</th>

				<th>
					Days
				</th>

				<th>
					Delete
				</th>
			</tr>

		</thead>
		
		<% @user.trains.each_with_index do |train, index| %>
		
		<tbody>

			<tr id="stop-<%= index %>">

				<td> 
					<b><%= train.line %></b> - <%= stops[train.stop] %> 
				</td>

				<% if Time.now.dst? %>
					<td> <%= (train.time + Time.zone_offset('CDT')).strftime("%I:%M %p") %> </td>
				<% else %>
					<td> <%= (train.time.strftime("%I:%M %p")) %> </td>
				<% end %>

				<td> 
					<%= day_converter(train.days) %>
				</td>
				
				<td> 
					<input class="pure-button delete unique" id="delete-train" title=<%=train.id%> type="submit" value="Delete" >
				</td>
			</tr>
		<% end %>
		</tbody>
	</table>
<% end %>

app/views/user/confirm.html.erb
<div class="confirm splash">
	<div class="confirm align">
		
		<div class="lead">
			
			<p id='message-center'>Enter your pin below or click 'Receive Pin' to be texted a new one.</p>
		
		</div>
		
		<form class='pure-form pure-form-stacked' id="submit-pin" action='/users/<%= @user.id %>/confirm' method="post">
			
			<input id="pin" type="text" name="pin" placeholder="Enter your pin" maxlength="4" autofocus>
			
			<input class="pure-button cta" type="submit" value="Submit Pin">
		
		</form>
		
		<form id='receive-pin' action="/users/<%= @user.id %>/code" method="post">

			<input class="hidden" type="text" value="<%= @user.id %>" name="id">

			<input class="pure-button cta" type="submit" value="Receive Pin">
		
		</form>

	</div>
</div>

app/views/user/profile.htlm.erb
<div class="confirm splash">
	<div class="confirm align">
		
		<div class="lead">
			
			<p id='message-center'>Enter your pin below or click 'Receive Pin' to be texted a new one.</p>
		
		</div>
		
		<form class='pure-form pure-form-stacked' id="submit-pin" action='/users/<%= @user.id %>/confirm' method="post">
			
			<input id="pin" type="text" name="pin" placeholder="Enter your pin" maxlength="4" autofocus>
			
			<input class="pure-button cta" type="submit" value="Submit Pin">
		
		</form>
		
		<form id='receive-pin' action="/users/<%= @user.id %>/code" method="post">

			<input class="hidden" type="text" value="<%= @user.id %>" name="id">

			<input class="pure-button cta" type="submit" value="Receive Pin">
		
		</form>

	</div>
</div>

app/views/user/profile.html.erb
<div class="profile">
	<div class="holder">

		<h1>Your phone number </h1>

		<hr class="divider" align="left">
		
		<div class="lead"><i><%= @user.phone.insert(3,'-').insert(7,'-') %></i></div>
		
		<div id="partials-div">
			<%= render partial: "stops_partial" %>
		</div>

		<h1 id="stop-header">Add a new stop</h1>
		
		<hr align="left" class="divider">
		
		<%= form_for(@train, :url => create_path(@user), html: {id: "new-stop", class: "pure-form pure-form-stacked"}) do |f| %>

			<fieldset>

				<div class="pure-g">

					<div class="pure-u-1 pure-u-md-1-2">

						<label for="select-line">Select Line</label>
						
						<select id="select-line" class="pure-input-1-2" name="line">
							
							<% cta_lines.each do |line| %>
								<option value="<%= line %>"><%= line %></option>
							<% end %>
						
						</select>
					
					</div>

					<div class="pure-u-1 pure-u-md-1-2 convenient" id="Red">
						
						<label for="select-stop">Select Stop</label>
						
						<select id="select-stop-red" class="pure-input-1-2" name="stop">
							
							<% red_line.each_key do |id| %>
								<option value="<%= id %>"><%= red_line[id] %></option>
							<% end %>	
						
						</select>
					
					</div>

					<div class="pure-u-1 pure-u-md-1-2 convenient hidden" id="Blue">
						
						<label for="select-stop">Select Stop</label>
						
						<select id="select-stop-blue" class="pure-input-1-2" name="stop">
							
							<% blue_line.each_key do |id| %>
								<option value="<%= id %>"><%= blue_line[id] %></option>
							<% end %>
						
						</select>
					
					</div>

					<div class="pure-u-1 pure-u-md-1-2 convenient hidden" id="Green">
						
						<label for="select-stop">Select Stop</label>
						
						<select id="select-stop-green" class="pure-input-1-2" name="stop">
							
							<% green_line.each_key do |id| %>
								<option value="<%= id %>"><%= green_line[id] %></option>
							<% end %>
						
						</select>
					
					</div>

					<div class="pure-u-1 pure-u-md-1-2 convenient hidden" id="Brown">
						
						<label for="select-stop">Select Stop</label>
						
						<select id="select-stop-brown" class="pure-input-1-2" name="stop">
							
							<% brown_line.each_key do |id| %>
								<option value="<%= id %>"><%= brown_line[id] %></option>
							<% end %>
						
						</select>
					
					</div>

					<div class="pure-u-1 pure-u-md-1-2 convenient hidden" id="Purple">
						
						<label for="select-stop">Select Stop</label>
						
						<select id="select-stop-purple" class="pure-input-1-2" name="stop">
							
							<% purple_line.each_key do |id| %>
								<option value="<%= id %>"><%= purple_line[id] %></option>
							<% end %>
						
						</select>
					
					</div>

					<div class="pure-u-1 pure-u-md-1-2 convenient hidden" id="PurpleExp">
						
						<label for="select-stop">Select Stop</label>
						
						<select id="select-stop-purpleexp" class="pure-input-1-2" name="stop">
							
							<% purple_line_exp.each_key do |id| %>
								<option value="<%= id %>"><%= purple_line_exp[id] %></option>
							<% end %>
						
						</select>
					
					</div>

					<div class="pure-u-1 pure-u-md-1-2 convenient hidden" id="Yellow">
						
						<label for="select-stop">Select Stop</label>
						
						<select id="select-stop-yellow" class="pure-input-1-2" name="stop">
							
							<% yellow_line.each_key do |id| %>
								<option value="<%= id %>"><%= yellow_line[id] %></option>
							<% end %>
						
						</select>
					
					</div>

					<div class="pure-u-1 pure-u-md-1-2 convenient hidden" id="Pink">
						
						<label for="select-stop">Select Stop</label>
						
						<select id="select-stop-pink" class="pure-input-1-2" name="stop">
							
							<% pink_line.each_key do |id| %>
								<option value="<%= id %>"><%= pink_line[id] %></option>
							<% end %>
						
						</select>
					
					</div>

					<div class="pure-u-1 pure-u-md-1-2 convenient hidden" id="Orange">
						
						<label for="select-stop">Select Stop</label>
						
						<select id="select-stop-orange" class="pure-input-1-2" name="stop">
							
							<% orange_line.each_key do |id| %>
								<option value="<%= id %>"><%= orange_line[id] %></option>
							<% end %>
						
						</select>
					
					</div>

					<div class="pure-u-1 pure-u-md-1-2">
						
						<label for="select-days">Select Days</label>
						
						<label class="pure-checkbox">
							<input id="monday" type=checkbox name="days[monday]" value="1">Monday
						</label>

						<label class="pure-checkbox">
							<input id="tuesday" type=checkbox name="days[tuesday]" value="2">Tuesday
						</label>

						<label class="pure-checkbox">
							<input id="wednesday" type=checkbox name="days[wednesday]" value="3">Wednesday
						</label>

						<label class="pure-checkbox">
							<input id="thursday" type=checkbox name="days[thursday]" value="4">Thursday
						</label>

						<label class="pure-checkbox">
							<input id="friday" type=checkbox name="days[friday]" value="5">Friday
						</label>

						<label class="pure-checkbox">
							<input id="saturday" type=checkbox name="days[saturday]" value="6">Saturday
						</label>

						<label class="pure-checkbox">
							<input id="sunday" type=checkbox name="days[sunday]" value="0">Sunday
						</label>

					</div>

					<div class="pure-u-1 pure-u-md-1-2">
						
						<label for="select-time">Select Time</label>
						
						<input id="select-time" class="pure-input-1-2" type="time" name="time">
					
					</div>

					<input id="user" class="hidden" type="text" value="<%= @user.id %>" name="id">

					<input id="add-stop" class="pure-button cta" type="submit" value="Add stop">
				
				</div>
			</fieldset>
		<%end%>

		<h1> The Danger Zone </h1>
		
		<hr align="left" class="divider">
			<%= form_for(:user, url: {action: "delete"}, html: {id: "delete-account-form"}) do |f| %>
			<input class="pure-button cta delete" type="submit" value="Delete account">
			<%end%>
	
	</div>
</div>

app/views/user/show.html.erb
<div class="confirm splash">
	<div class="confirm align">
		
		<div class="lead">
			
			<p id='message-center'>Enter your pin below or click 'Receive Pin' to be texted a new one.</p>
		
		</div>

		<%= form_for(:user, url: {action: "profile"}, html: {class: 'pure-form pure-form-stacked', id: "submit-pin"}) do |f| %>

			<%= f.text_field :password_digest, placeholder: "Enter your pin", id: "pin", name: "pin", autofocus: true, maxlength: 4, :value => "" %>

			<input class="pure-button cta" type="submit" value="Submit Pin">
			<%end%>

		<%= form_for(:user, url: {action: "code"}, html: {id: "recieve-pin"}) do |f| %>
			<input class="pure-button cta" type="submit" value="Receive Pin">
			<%end%>
	</div>
</div>